### PR TITLE
WIP: TypeScript

### PR DESCRIPTION
**Pull request by eknowles**
Not sure how you feel about this, but I made a PR just in case. It's still a WIP PR as I need to add some tests and try it out.

This merges the three Index/Function/Role creation into a single file, just remove duplicates.

### CODE REVIEW

**Comment by Plazide** [comment]
I was actually planning on converting to typescript, so that's great. And I didn't like having 3 different function that did essentially the same thing, so merging those into one function is a big improvement.

I'll wait with merging, but I really like the changes you've made! :)

**Comment by eknowles** [comment]
I've got some examples added, and tested now.
What I think would be good is to have it work with node.js or as a cli, so looking at removing some of the path stuff?

**Comment by Plazide** [comment]
How do you imagine it working with node.js? Just exporting the `uploadResource` function?

Anyway, I tried out your changes and it is failing with every resource. I get the `document data is not valid` error. It works as expected on the published version, so it does not seem to be an issue with my resources. I haven't been able to figure out why this happens. I'll try and debug more later.

Also, the reason why I used a double space after the checkmark icons was that the icon overlapped the text in the vscode terminal. Like this: bild. Though I realize now, that it looks right with one space in the normal terminal. So the unicode icon seems to be inconsistent, it might be worth exploring another way to indicate success/failure. Maybe just changing the color of the text to green/red. what do you think?

**Comment by eknowles** [comment]
my branch is still very much wip

1. node: yes, I think maybe replacing the console logs with [debug](https://www.npmjs.com/package/debug) ? and then splitting the `fs` methods out and adding a return object (and format/print this with the CLI)

2. I see 😄 I use WebStorm so I didn't see the VSCode issue. I've replaced the unicode with https://fsymbols.com/signs/tick/ ? and added the two spaces..

 
Screenshot 2020-07-07 at 23 35 49
Screenshot 2020-07-07 at 23 35 04
Screenshot 2020-07-07 at 23 34 32

Weirdly in bash it has two spaces as normal, a bit odd. What are your thoughts on using `ink` for the CLI output?

Some simple examples like `jest` don't use ascii icons at all, (use background color with [success] etc)
https://github.com/vadimdemedes/ink/blob/master/examples/jest/test.js

I've built my own terminal application for jira/azure that does use tick/cross

https://github.com/mink-org/mink/blob/master/packages/components/src/table/table.component.tsx

As an example ^

**Comment by Plazide** [comment]
Sure, we could use `debug` instead of `console.log`. Splitting out the fs statements is something I was planning on doing, so we should absolutely do that.

Didn't know about `ink`, but it looks very useful for this project. I think handling the output the `jest` way would be better, just a green [success] or red [fail] before the status message.

**Comment by maxfi** [comment]
For the cli perhaps https://github.com/infinitered/gluegun could be useful. Might be overkill though...

**Comment by Plazide** [comment]
`gluegun` is probably a bit overkill as you say. I don't think we'll use half the features it offers.

**Comment by eknowles** [comment]
I found a bug in the original code when implementing ink, basically the await doesn't actually wait, so some of the uploads where happening in different orders, this caused functions to be uploaded before indexes etc, which meant in brand new databases, fauna would throw and error saying resource does not exist.
This was down to the way the node fs lib was being used sync, I've replaced these with promise based fs method and it solved the issue, and shows the real progress when uploading.

I'm quite busy with work but will be able to push these changes later tonight or tomorrow.

**Comment by Plazide** [comment]
That's great, @eknowles 

I did notice that the resources weren't being uploaded in the expected order, but never found the reason for it. It would probably have caused a lot of problems in the future (aside from the problems it's already caused), so it's a very important fix.

I really appreciate the effort you're putting in to this. I love what you've done so far, your're improving the quality of this project far beyond what I had in mind from the beginning. It'll be great to build on top of what you've done.

**Pull request closed without merging**
